stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - make venv_install
    - make test
  only:
    - master
  cache:
    paths:
      - venv/

build_job:
  stage: build
  script:
    - echo "Create build"
  only:
    - master

deploy_dev_job:
  stage: deploy
  script:
    - echo "Make deploy"
  only:
    - master
