before_script:
  - make venv_install
  - make db_test_create
  - bash -c "cd frontend && make install"

stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - make test
  only:
    - master

build_job:
  stage: build
  script:
    - echo "Create build"
  only:
    - master

deploy_dev_job:
  stage: deploy
  script:
    - echo "Make deploy"
  only:
    - master
