"""empty message

Revision ID: 874e8dadd617
Revises: None
Create Date: 2016-02-22 12:13:06.866259

"""

# revision identifiers, used by Alembic.
revision = '874e8dadd617'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('checking_account', sa.String(length=14), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'RUB', 'UAH', 'EUR'), nullable=False),
    sa.Column('mfo', sa.String(length=6), nullable=False),
    sa.Column('okpo', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=True),
    sa.Column('director_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_systems',
    sa.Column('paysys_id', sa.Enum('PAY_PAL', 'BIT_COIN', 'VISA_MASTER'), nullable=False),
    sa.Column('paysys_name', sa.String(length=80), nullable=False),
    sa.Column('paysys_login', sa.String(length=255), nullable=False),
    sa.Column('paysys_password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('paysys_id')
    )
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_algorithm', sa.Enum('MD5', 'SHA1'), nullable=False),
    sa.Column('sign_key', sa.String(length=127), nullable=False),
    sa.Column('succeed_url', sa.String(length=255), nullable=False),
    sa.Column('failure_url', sa.String(length=255), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('notify', sa.Enum('EMAIL', 'PHONE'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=32), nullable=False),
    sa.Column('merchant_account_id', sa.Integer(), nullable=False),
    sa.Column('merchant_info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_account.id'], ),
    sa.ForeignKeyConstraint(['merchant_info_id'], ['merchant_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_name')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=32), nullable=False),
    sa.Column('store_url', sa.String(length=255), nullable=False),
    sa.Column('store_identifier', sa.String(length=127), nullable=False),
    sa.Column('category', sa.Enum('Dress', 'Children', 'Computers'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('show_logo', sa.Boolean(), nullable=True),
    sa.Column('store_settings_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['store_settings_id'], ['store_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_identifier')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('manager')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('store_settings')
    op.drop_table('payment_systems')
    op.drop_table('merchant_info')
    op.drop_table('merchant_account')
    ### end Alembic commands ###
