"""empty message

Revision ID: 8e30f7962808
Revises: 874e8dadd617
Create Date: 2016-03-01 17:17:16.422585

"""

# revision identifiers, used by Alembic.
revision = '8e30f7962808'
down_revision = '874e8dadd617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_ccy', sa.String(length=3), nullable=True),
    sa.Column('ccy', sa.String(length=3), nullable=True),
    sa.Column('sale', sa.Float(), nullable=True),
    sa.Column('buy', sa.Float(), nullable=True),
    sa.Column('commit_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    ### end Alembic commands ###
